# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/mattias.hedberg/Documents/repositories/FakemonCreator/creator/ui/FakemonCreator.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setObjectName("MainWindow")
        self.resize(1178, 933)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.list_pokemon = QtWidgets.QListWidget(self.centralwidget)
        self.list_pokemon.setGeometry(QtCore.QRect(10, 10, 256, 731))
        self.list_pokemon.setObjectName("list_pokemon")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(340, 270, 160, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.skills_list = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.skills_list.setObjectName("skills_list")
        self.verticalLayout.addWidget(self.skills_list)
        self.add_skill = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.add_skill.setObjectName("add_skill")
        self.verticalLayout.addWidget(self.add_skill)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(330, 580, 160, 131))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.senses_list = QtWidgets.QListWidget(self.verticalLayoutWidget_6)
        self.senses_list.setObjectName("senses_list")
        self.verticalLayout_6.addWidget(self.senses_list)
        self.add_senses = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        self.add_senses.setObjectName("add_senses")
        self.verticalLayout_6.addWidget(self.add_senses)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(360, 410, 160, 168))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.abilities_list = QtWidgets.QListWidget(self.verticalLayoutWidget_7)
        self.abilities_list.setObjectName("abilities_list")
        self.verticalLayout_7.addWidget(self.abilities_list)
        self.add_ability = QtWidgets.QComboBox(self.verticalLayoutWidget_7)
        self.add_ability.setObjectName("add_ability")
        self.verticalLayout_7.addWidget(self.add_ability)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(270, 760, 641, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.evolve_into_list = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.evolve_into_list.setObjectName("evolve_into_list")
        self.verticalLayout_16.addWidget(self.evolve_into_list)
        self.add_evolution = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.add_evolution.setObjectName("add_evolution")
        self.verticalLayout_16.addWidget(self.add_evolution)
        self.horizontalLayout.addLayout(self.verticalLayout_16)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.evolve_level_gain = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.evolve_level_gain.setObjectName("evolve_level_gain")
        self.horizontalLayout.addWidget(self.evolve_level_gain)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.evolve_points_gain = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.evolve_points_gain.setObjectName("evolve_points_gain")
        self.horizontalLayout.addWidget(self.evolve_points_gain)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(740, 160, 391, 530))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_13.addWidget(self.label_17)
        self.moves_tm_list = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.moves_tm_list.setObjectName("moves_tm_list")
        self.verticalLayout_13.addWidget(self.moves_tm_list)
        self.add_tms = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.add_tms.setObjectName("add_tms")
        self.verticalLayout_13.addWidget(self.add_tms)
        self.gridLayout.addLayout(self.verticalLayout_13, 0, 1, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.moves_10_list = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.moves_10_list.setObjectName("moves_10_list")
        self.verticalLayout_10.addWidget(self.moves_10_list)
        self.add_level_10_moves = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.add_level_10_moves.setObjectName("add_level_10_moves")
        self.verticalLayout_10.addWidget(self.add_level_10_moves)
        self.gridLayout.addLayout(self.verticalLayout_10, 1, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.moves_6_list = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.moves_6_list.setObjectName("moves_6_list")
        self.verticalLayout_9.addWidget(self.moves_6_list)
        self.add_level_6_moves = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.add_level_6_moves.setObjectName("add_level_6_moves")
        self.verticalLayout_9.addWidget(self.add_level_6_moves)
        self.gridLayout.addLayout(self.verticalLayout_9, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.moves_starting_list = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.moves_starting_list.setObjectName("moves_starting_list")
        self.verticalLayout_8.addWidget(self.moves_starting_list)
        self.add_starting_moves = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.add_starting_moves.setObjectName("add_starting_moves")
        self.verticalLayout_8.addWidget(self.add_starting_moves)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_11.addWidget(self.label_15)
        self.moves_14_list = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.moves_14_list.setObjectName("moves_14_list")
        self.verticalLayout_11.addWidget(self.moves_14_list)
        self.add_level_14_moves = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.add_level_14_moves.setObjectName("add_level_14_moves")
        self.verticalLayout_11.addWidget(self.add_level_14_moves)
        self.gridLayout.addLayout(self.verticalLayout_11, 2, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_12.addWidget(self.label_16)
        self.moves_18_list = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.moves_18_list.setObjectName("moves_18_list")
        self.verticalLayout_12.addWidget(self.moves_18_list)
        self.add_level_18_moves = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.add_level_18_moves.setObjectName("add_level_18_moves")
        self.verticalLayout_12.addWidget(self.add_level_18_moves)
        self.gridLayout.addLayout(self.verticalLayout_12, 2, 1, 1, 1)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(570, 270, 160, 475))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_14.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.vulnerabilities_list = QtWidgets.QListWidget(self.verticalLayoutWidget_14)
        self.vulnerabilities_list.setObjectName("vulnerabilities_list")
        self.verticalLayout_3.addWidget(self.vulnerabilities_list)
        self.add_vulnerabilities = QtWidgets.QComboBox(self.verticalLayoutWidget_14)
        self.add_vulnerabilities.setObjectName("add_vulnerabilities")
        self.verticalLayout_3.addWidget(self.add_vulnerabilities)
        self.verticalLayout_14.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.resistances_list = QtWidgets.QListWidget(self.verticalLayoutWidget_14)
        self.resistances_list.setObjectName("resistances_list")
        self.verticalLayout_4.addWidget(self.resistances_list)
        self.add_resistances = QtWidgets.QComboBox(self.verticalLayoutWidget_14)
        self.add_resistances.setObjectName("add_resistances")
        self.verticalLayout_4.addWidget(self.add_resistances)
        self.verticalLayout_14.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.immunities_list = QtWidgets.QListWidget(self.verticalLayoutWidget_14)
        self.immunities_list.setObjectName("immunities_list")
        self.verticalLayout_5.addWidget(self.immunities_list)
        self.add_immunities = QtWidgets.QComboBox(self.verticalLayoutWidget_14)
        self.add_immunities.setObjectName("add_immunities")
        self.verticalLayout_5.addWidget(self.add_immunities)
        self.verticalLayout_14.addLayout(self.verticalLayout_5)
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(310, 130, 310, 134))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.armor_class = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.armor_class.setObjectName("armor_class")
        self.horizontalLayout_2.addWidget(self.armor_class)
        self.verticalLayout_15.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_3.addWidget(self.label_19)
        self.hit_points = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.hit_points.setObjectName("hit_points")
        self.horizontalLayout_3.addWidget(self.hit_points)
        self.verticalLayout_15.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        self.hit_dice = QtWidgets.QComboBox(self.verticalLayoutWidget_15)
        self.hit_dice.setObjectName("hit_dice")
        self.horizontalLayout_4.addWidget(self.hit_dice)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_10.addWidget(self.label_25)
        self.saving_throw1_pokemon = QtWidgets.QComboBox(self.verticalLayoutWidget_15)
        self.saving_throw1_pokemon.setObjectName("saving_throw1_pokemon")
        self.horizontalLayout_10.addWidget(self.saving_throw1_pokemon)
        self.saving_throw2_pokemon = QtWidgets.QComboBox(self.verticalLayoutWidget_15)
        self.saving_throw2_pokemon.setObjectName("saving_throw2_pokemon")
        self.horizontalLayout_10.addWidget(self.saving_throw2_pokemon)
        self.verticalLayout_15.addLayout(self.horizontalLayout_10)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(310, 30, 821, 91))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_8.addWidget(self.label_24)
        self.species = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.species.setFont(font)
        self.species.setObjectName("species")
        self.horizontalLayout_8.addWidget(self.species)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_6.addWidget(self.label_22)
        self.type1_pokemon = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.type1_pokemon.setObjectName("type1_pokemon")
        self.horizontalLayout_6.addWidget(self.type1_pokemon)
        self.type2_pokemon = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.type2_pokemon.setObjectName("type2_pokemon")
        self.horizontalLayout_6.addWidget(self.type2_pokemon)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_7.addWidget(self.label_23)
        self.sr_pokemon = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.sr_pokemon.setObjectName("sr_pokemon")
        self.horizontalLayout_7.addWidget(self.sr_pokemon)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_11.addWidget(self.label_26)
        self.level = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.level.setObjectName("level")
        self.horizontalLayout_11.addWidget(self.level)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_11)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_5.addWidget(self.label_21)
        self.index_number = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.index_number.setObjectName("index_number")
        self.horizontalLayout_5.addWidget(self.index_number)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1178, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionNew_Pokemon = QtWidgets.QAction(self)
        self.actionNew_Pokemon.setObjectName("actionNew_Pokemon")
        self.actionNew_Move = QtWidgets.QAction(self)
        self.actionNew_Move.setObjectName("actionNew_Move")
        self.actionNew_Ability = QtWidgets.QAction(self)
        self.actionNew_Ability.setObjectName("actionNew_Ability")
        self.actionExit = QtWidgets.QAction(self)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen_Standard_Pokemon = QtWidgets.QAction(self)
        self.actionOpen_Standard_Pokemon.setObjectName("actionOpen_Standard_Pokemon")
        self.actionOpen_Move = QtWidgets.QAction(self)
        self.actionOpen_Move.setObjectName("actionOpen_Move")
        self.actionOpen = QtWidgets.QAction(self)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew_Pokemon)
        self.menuFile.addAction(self.actionNew_Move)
        self.menuFile.addAction(self.actionNew_Ability)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Standard_Pokemon)
        self.menuFile.addAction(self.actionOpen_Move)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Proficient Skills"))
        self.label_6.setText(_translate("MainWindow", "Senses"))
        self.label_7.setText(_translate("MainWindow", "Abilities"))
        self.label_8.setText(_translate("MainWindow", "Evolve into"))
        self.label_9.setText(_translate("MainWindow", "at level"))
        self.label_11.setText(_translate("MainWindow", "gain"))
        self.label_10.setText(_translate("MainWindow", "points to add to its ability scores"))
        self.label_17.setText(_translate("MainWindow", "Learnables TMs"))
        self.label_14.setText(_translate("MainWindow", "Level 10 Moves"))
        self.label_13.setText(_translate("MainWindow", "Level 6 Moves"))
        self.label_12.setText(_translate("MainWindow", "Starting Moves"))
        self.label_15.setText(_translate("MainWindow", "Level 14 Moves"))
        self.label_16.setText(_translate("MainWindow", "Level 18 Moves"))
        self.label_3.setText(_translate("MainWindow", "Vulnerabilities"))
        self.label_4.setText(_translate("MainWindow", "Resistances"))
        self.label_5.setText(_translate("MainWindow", "Immunities"))
        self.label_18.setText(_translate("MainWindow", "Armor Class"))
        self.label_19.setText(_translate("MainWindow", "Hit Points"))
        self.label_20.setText(_translate("MainWindow", "Hit Dice"))
        self.label_25.setText(_translate("MainWindow", "Saving Throws"))
        self.label_24.setText(_translate("MainWindow", "Species"))
        self.label_22.setText(_translate("MainWindow", "Types"))
        self.label_23.setText(_translate("MainWindow", "SR"))
        self.label_26.setText(_translate("MainWindow", "Level"))
        self.label_21.setText(_translate("MainWindow", "Index #"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew_Pokemon.setText(_translate("MainWindow", "New Pokemon"))
        self.actionNew_Move.setText(_translate("MainWindow", "New Move"))
        self.actionNew_Ability.setText(_translate("MainWindow", "New Ability"))
        self.actionExit.setText(_translate("MainWindow", "Close"))
        self.actionOpen_Standard_Pokemon.setText(_translate("MainWindow", "Open Pokemon"))
        self.actionOpen_Move.setText(_translate("MainWindow", "Open Move"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))

